<a href="https://colab.research.google.com/github/GouriNayak/DMDW/blob/main/DataSetImporting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
url = 'https://raw.githubusercontent.com/GouriNayak/DMDW/main/Data.csv'

In [ ]:
import pandas as pd

In [ ]:
data =pd.read_csv(url)

In [ ]:
data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving Data.csv to Data (1).csv


In [ ]:
data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [ ]:
import io

In [ ]:
df1 = pd.read_csv(io.BytesIO(uploaded['Data.csv']))

In [ ]:
data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [ ]:
import numpy

In [ ]:
arr=numpy.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

In [ ]:
print('np._version_')

np._version_


In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>
